name: Fetch PRs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      users:
        description: 'List of users to track'
        required: true
        default: 'ananos,Pyrromanis,gntouts,papazof'
      repos:
        description: 'List of repositories to check'
        required: true
        default: 'kata-containers/kata-containers,unikraft/unikraft,containerd/containerd,sigstore/rekor-monitor,dragonflyoss/nydus,containerd/ttrpc-rust'


jobs:
  fetchPullRequests:
    name: "Running for users: ${{ github.event.inputs.users }} and repos: ${{ github.event.inputs.repos }}"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run script to fetch PRs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERS: ${{ github.event.inputs.users }}
        REPOS: ${{ github.event.inputs.repos }}
      run: |
        python tracker.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/all_prs.json
        git pull
        git commit -m 'Update PR report'
        git push

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
